---
- name: Test Docker Access
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Test running docker ps with sudo
      shell: sudo docker ps -a
      register: docker_ps_output # Register the output for inspection
    - name: Print docker ps output
      debug:
        var: docker_ps_output.stdout_lines